name: "Nix CI"
on:
  pull_request:
  push:
jobs:
  nix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Nix Flake Check
      run: nix -Lv flake check

    - uses: cachix/cachix-action@v10
      with:
        name: emacsng
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

    - name: Run Emacsng Exec
      run: nix -Lv run .#emacsng-noNativeComp -- --version
